AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OrderAgent Lambda Deployment

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64
    Environment:
      Variables:
        SPRING_PROFILES_ACTIVE: lambda

Resources:
  OrderAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrderAgentFunction
      CodeUri: .   # ← 현재 build.gradle이 있는 루트
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
    Metadata:
      SamResourceId: OrderAgentFunction
